// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rvpoywozsziywtxynhse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ2cG95d296c3ppeXd0eHluaHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDAyNDksImV4cCI6MjA3MDU3NjI0OX0.0tK4UElS1SOZeprTKsgI6BxDy3hnc-GhYOWV7LZ1lXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});